---
 - name: Removing old records in the repl_monitor table
   cron:
     name: "Removing repl_monitor records older than 4 days"
     minute: "{{ item.repmgr_cron_minute }}"
     hour: "{{ item.repmgr_cron_hour }}"
     day: "{{ item.repmgr_cron_day }}"
     month: "{{ item.repmgr_cron_month }}"
     weekday: "{{ item.repmgr_cron_weekday }}"
     job: "{{ item.repmgr_cron_job }}"
     state: present

     with_items: "{{ repmgr_cron }}"


