---

- include: install.yml
  tags: [repmgr, repmgr-install]

- include: configure.yml
  tags: [repmgr, repmgr-configure]

- include: bootstrap.yml
  when: repmgr_bootstrap|bool
  tags: [repmgr, repmgr-bootstrap]

- include: cron_jobs.yml
  when: repmgr_cron_status
  tags: [repmgr, repmgr-cron]

